databases:
  - name: cookwith
    databaseName: cookwith_db
    user: cookwith
    region: singapore

services:
  - type: web
    name: cookwith
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cookwith_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false